### ISSUE TITLE
catch user input error 

### ISSUE THREAD

**Issue by TomMelt** [TomMelt/mdb#14]
For example, if user types `interact 0'` instead of `interact 0` they will get a rather annoying error that exits the debugging session.

```python
(mdb 0-7) interact 0'
Traceback (most recent call last):
  File "/home/melt/miniconda3/envs/mdb/bin/mdb", line 33, in <module>
    sys.exit(load_entry_point('mdb', 'console_scripts', 'mdb')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melt/miniconda3/envs/mdb/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melt/miniconda3/envs/mdb/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/melt/miniconda3/envs/mdb/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melt/miniconda3/envs/mdb/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melt/miniconda3/envs/mdb/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/melt/sync/cambridge/projects/side/mdb/mdb/mdb_attach.py", line 115, in attach
    mshell.cmdloop()
  File "/home/melt/miniconda3/envs/mdb/lib/python3.12/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
           ^^^^^^^^^^^^^^^^^
  File "/home/melt/miniconda3/envs/mdb/lib/python3.12/cmd.py", line 217, in onecmd
    return func(arg)
           ^^^^^^^^^
  File "/home/melt/sync/cambridge/projects/side/mdb/mdb/mdb_shell.py", line 114, in do_interact
    rank: int = int(line)
                ^^^^^^^^^
ValueError: invalid literal for int() with base 10: "0'"
```

It is probably sufficient to just catch the `ValueError` and return a message like `Optional argument to command must be a string containing comma- and/or hyphen-separated numbers e.g., command 1,2-5 [command]. For help type "?" or "help"`

**Comment by TomMelt** [comment]
actually it should be sufficient to fix the regex in `mdb/mdb_shell.py` from this

```python
if re.match(r"[0-9,-]+", commands[0]):
```
To this:
```python
if re.match(r"[0-9,-]+\s", commands[0]):
```
